name: React Native CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.1.0'

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      - name: Install Snyk CLI
        run: |
          npm install -g snyk@1.1288.0

      - name: Run Snyk security scan
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects

      - name: Run Snyk Monitor
        run: |
          snapshot_link=$(snyk monitor --all-projects | grep "Explore this snapshot at" | sed 's/Explore this snapshot at //')
          echo "[Snyk Monitor link]($snapshot_link)" >> $GITHUB_STEP_SUMMARY

      - name: Publish Test Report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: test-reports
          target-folder: test-reports/${{github.sha}}/${{github.run_id}}/${{github.run_attempt}}
          force: false
          clean: true

      - name: URL for test report generated by jest
        run: echo "[TEST REPORT GENERATED BY JEST](https://sathyarupa.github.io/airport-app-frontend/test-reports/${{github.sha}}/${{github.run_id}}/${{github.run_attempt}}/test-report.html)" >> $GITHUB_STEP_SUMMARY
